### ISSUE TITLE
Mandatory use of XSL transform is not being used

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#100]
I read this documentation about PEM 111, https://www.nwsurreyccg.nhs.uk/stay-informed/documents/nhs-111-1/391-appendix-d-it-standards/file      see 11.7. it said a specific transformed XSL must be used against CDA. My understanding, this is not being currently being used looking from the payload returned, and if this transformed being used, most of the transformation may not be required, probably just need to get the patient, transformed html text, and attachment data (and mimetype) into FHIR response.

**Comment by michael-kainos** [comment]
This looks like a requirement for 111 sending systems, NHS testing did not highlight this as a requirement. Closing with Status as WONT FIX.

**Comment by Kusnaditjung** [comment]
Hi, My understanding working previously with MIM specs, the transform is not for the sending side, but for the recipient side.

**Comment by michael-kainos** [comment]
@Kusnaditjung this section describes "CDA messages should be rendered using specific XML transforms" The requirement of  the 111 PEM adapter was to transform to JSON FHIR only. I think this could be describing a transformation at the HA side.

**Comment by Kusnaditjung** [comment]
After the discussion with NHSD Architects (David Water and Adam Lee), the stylesheet is not a mandatory requirement for NHS 111. For UI rendering Parts, it will depend on the consumer system to render as it wishes, at the moment they don't seem to be aware of any requirements on the UI rendering parts. However, for KAINOS, there may need a check to see if they also translate Section 2 - Section 7. So, there may be more answer for KAINOS for this part.
