### ISSUE TITLE
CDA requirements

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#101]
Apparently, there should be requirement documents that the NHS111 adapter must fulfill based on what it does.  This is particularly crucial when suppliers need to integrate their products and must meet the risks assurance process. A number of elements of NHS 111, are Web service ITK and CDA functionality (which include GP System workflow), and DOS, the previous two can be retrieved from TRUD, DOS can be seen in the NHSD development website.  My question is about CDA requirements, how much of it we need to test against the adapter, as CDA requirements span across adapter (because adapter translates CDA) and GP systems (still need to adhere to the expected workflow).

**Comment by michael-kainos** [comment]
Not sure i understand the question here, please provide more information on this. STATUS IS NEEDS MORE INFORMATION

**Comment by Kusnaditjung** [comment]
I mean this package (download from TRUD), NHS Interoperability Toolkit CDA Functional Requirements
This is the requirement for the CDA document which is transported via ITK. But I am not sure whether NHS 111 is assured against this or not, so I ask this question

**Comment by michael-kainos** [comment]
@Kusnaditjung can you confirm this is the document name you require:
NHS111DMS-Version2-0-RC1

**Comment by Kusnaditjung** [comment]
From a discussion with NHSD architect (David Waters and Adam Lees), the CDA requirements will be needed for the adapter as it contains CDA documents, and NHS 111 appears to be CDA accreditated. All the errors need to communicate as a syncronous response.
