### ISSUE TITLE
Question: Various Validation Error response

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#103]
I reckon if the payload is invalid it will give a SOAP fault response, what is the expected outcome if (a) the SOAP element is missing or invalid (b) ITK element is missing or invalid (c) CDA element is missing or invalid.

**Comment by michael-kainos** [comment]
These may be resolved in the next 111 PEM image release at the end of our current sprint. Will leave this Open to re-test once release has been provided.
Status: ON HOLD
