### ISSUE TITLE
Missing acknowlegement functionality

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#104]
In the GP system, when a document is rejected because of the various reason (wrong patient, etc), the business acknowledgement should be sent (ITK specification), but the adapter at the moment does not allow this to happen, and also it does not pass the flag 'is business ack required' from ITK envelope, as it just transforms the CDA document and ignores all ITK information (some of them required by the GP system)

**Comment by michael-kainos** [comment]
Adapter only handles a synchronous reply. All ITK test responses have been verified by NHSD as containing all required elements. No ITK example provided by NHSD have business ack required flag included in the data set.

**Comment by Kusnaditjung** [comment]
ok, so in that case, I assume all previously errors that should be in infrastructure acknowledgment, it now should manifest itself as a sync error (e.g ITK error related), and business ack requested is ignored if it is present
