### ISSUE TITLE
SOAPAction header missing from testscript example

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#105]
I assume there is a client requirement to send SOAPAction header to SOAP (https://www.w3.org/TR/2000/NOTE-SOAP-20000508/), the test script example does not have this. Though I am not sure if the server (adapter) needs to validate against this or not.

**Comment by michael-kainos** [comment]
ITK assurance tests are passing without this header and no requirement has been given by NHSD for this. Closing as WONT FIX status

**Comment by Kusnaditjung** [comment]
My understand the ITK assurance tests will not test everything.. so if it is not passed then it is not good, but if passed, we still to make sure other parts still pass the accreditation .

**Comment by Kusnaditjung** [comment]
My understand the ITK assurance tests will not test everything.. so if it is not passed then it is not good, but if passed, we still to make sure other parts still pass the accreditation .
