### ISSUE TITLE
Wrong/inconsistent version of FHIR being used

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#106]
What Fhir format version we use for queue, my understanding is R4, but looking from the example there is element that only exist in R3, such as Encounter-> incomingReferral,  Encounter->reason, Diagnosis->role,  in R4 this should be Encounter->basedOn, Encounter->reasonCode, and Diagnosis->use respectively, also ReferralRequest seems only being used in DSTU2 and STU3, and has been superseded in R4 as ServiceRequest. Similar thing happen on Careplan, Consent, Condition (some of the fields has changed

**Comment by michael-kainos** [comment]
The requirement was to transform CDA into FHIR STU3, closing this as WONT FIX status
