### ISSUE TITLE
CDA Requirements schema and schematron validation

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#115]
**Description**

The NHS 111 CDA message should be a valid NHS 111 CDA message, there is two schema validation that needs to be performed against the message. 
- schema validation against on wire CDA format which is POCD_MT000002UK01.xsd
- transformed to template format and validate against schema for NHS 111 message (POCD_MT200001GB02.xsd), which is specified in the ClinicalDocument->npfitlc:messageType.

These validations can be found in the NPFIT-FNT-TO-TAR-0081.03 CDA Document Technical Requirements v2.0.pdf from **NHS Interoperability Toolkit CDA Functional Requirements** pack and can be dowloaded from TRUD. 

My observation is that the templated schema may not be performed, as there is an element that is not in the POCD_MT200001GB02, but they are processed as just a valid NHS 111 message. 

The suspect element is custodian telecom and addr , both elements are not in the specification, but they present in the example and are processed as just a valid NHS 111 message.

```xml
   <custodian typeCode="CST">
              <npfitlc:contentId root="2.16.840.1.113883.2.1.3.2.4.18.16"
                                 extension="COCD_TP145018UK03#AssignedCustodian"/>
              <assignedCustodian classCode="ASSIGNED">
                <templateId root="2.16.840.1.113883.2.1.3.2.4.18.2"
                            extension="COCD_TP145018UK03#AssignedCustodian"/>
                <representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
                  <templateId root="2.16.840.1.113883.2.1.3.2.4.18.2"
                              extension="COCD_TP145018UK03#representedCustodianOrganization"/>
                  <id root="2.16.840.1.113883.2.1.3.2.4.19.1" extension="5L3"/>
                  <name>Broomfield Foundation Trust</name>
                  <telecom use="WP" value="tel:0123476895"/>
                  <addr use="WP">
                    <streetAddressLine>Broomfield Hospital</streetAddressLine>
                    <streetAddressLine>Bocking End</streetAddressLine>
                    <postalCode>CM7 9AB</postalCode>
                    <city>Braintree</city>
                    <county>Essex</county>
                    <country>UK</country>
                  </addr>
                </representedCustodianOrganization>
              </assignedCustodian>
            </custodian>
```

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the the example of CDA in the ..\service\src\integration-test\resources\xml\ITK_Report_request.xml
* Send the message, the response should fail with a templated schema validation error.

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**

The response returns a SOAP Fault (as a consequence of sync mode of the adapter) with error text and/or diagnostic:
* CDA Message Definition Schema validation failure. Detail: "{0}" => if templated cda validation

The OID for this error is 2.16.840.1.113883.2.1.3.2.4.17.227, and the error code can be found from the below link.

See point to point error documentation, NPFIT-FNT-TO-TAR-0083 02 CDA Interoperability - Point to Point Error Codes v1.0 from **NHS Interoperability Toolkit CDA Functional Requirements** pack.

**Comment by michael-kainos** [comment]
@Kusnaditjung find attached the requirement source document reference by Kainos and the list of test cases related to the requirements that was required by NHSD Assurance


[111 PEM Kainos Assurance Cases.xlsx](https://github.com/nhsconnect/integration-adaptor-111/files/5408764/111.PEM.Kainos.Assurance.Cases.xlsx)

[ITK2.2-Supplier Certified Requirements Coverage v8.5.pdf](https://github.com/nhsconnect/integration-adaptor-111/files/5408780/ITK2.2-Supplier.Certified.Requirements.Coverage.v8.5.pdf)

**Comment by Kusnaditjung** [comment]
I think schema and templated schema validation is within MOD-VAL-01 (MUST), this said it must be configurable. I think the NHS 111 adapter only work for NHS 111 and not other CDA document type (discharge, out of hours, etc), so the configuration aspect can be skipped. 

I think the additional content validation is within MOD-VAL-04 (SHOULD)

**Comment by dawidskainos** [comment]
@Kusnaditjung schema validation is performed. However, OID checks you described above are not part of schema validation. These could be performed as part of  "additional content validation" - but there was no specific requirement to validate them, so it was never implemented.

**Comment by Kusnaditjung** [comment]
@dawidskainos   yep it says SHOULD for content validation. For schema validation, there are two schema validation (one is for CDA, and one is templated CDA). For my other observation (in the slack chat) for version 0.10  apparently, the templated CDA has not been performed yet on that version, because there are some elements that should not be there (I check against the NHS 111 DMS in TRUD) for the custodian. Do I need to change the description to limit the issue to schema validation or create a new issue?

**Comment by dawidskainos** [comment]
@Kusnaditjung can you please narrow down the description to reflect what you think is an issue now? We might need to check with NHS whether we want to fix it.

**Comment by michael-kainos** [comment]
@Kusnaditjung  closing this please comment here with new issue raised

**Comment by Kusnaditjung** [comment]
this is closed due to schematron validation is optional.
I have created a new issue for just the schema validation #131
