### ISSUE TITLE
The interaction or interaction type (primary/copy) is missing in the output

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#117]
**Description**

The NHS 111 does have associated interaction in the ITK envelope, but they are not getting passed to the message queue (and also not passed in the queue header). So it is impossible to know whether the transaction is for the primary/copy recipient. The way the document is rendered on the screen, or how the document is treated in the workflow also depending on whether that the document recipient is the copy / primary recipient. 

The indication of primary or copy can be extracted from the itk handling message spec value for key 'urn:nhs-itk:ns:201005:interaction', eg. in the example below itk:interaction:**primary**Emergencyxxxx), which indicate a primary

```xml
 <!-- handlingSpecification contains the interaction id from the 111 specification - key is always fixed; value varies depending on recipient -->
                <itk:handlingSpecification>
                    <itk:spec value="urn:nhs-itk:interaction:primaryEmergencyDepartmentRecipientNHS111CDADocument-v2-0"
                              key="urn:nhs-itk:ns:201005:interaction"/>
                </itk:handlingSpecification>

```

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the valid a CDA in the payload, and send
* Inspect the message queue, nowhere to know if it is for copy/primary recipient. 

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
High, impact on supplier integration

**Priority**
Not urgent

**Expected Behavior**
The ITK interaction (or copy/primary recipient type) is output in the queue header or somewhere.

**Comment by michael-kainos** [comment]
This requirement was not visible to us. I will raise this with NHS to confirm

**Comment by davidwaters33** [comment]
This can be derived from the participant in the 111 Report where the typeCode is 'REFT'.  If the participant is populated with the GP practice, then this is 'FOR ACTION', otherwise this is 'FOR INFORMATION'

In the Encounter Report, this recipient should have been mapped to ReferralRequest.recipient as a HealthcareService

**Comment by Kusnaditjung** [comment]
My understanding is CDA is created once with primary and copy recipients. But the ITK envelope decides which destination of the message. So for one CDA, you may send multiple times to a different destination, thus using different ITK interactions (copy and primary). So, the issue I raised is not about what is in the CDA document, but in the ITK envelope. However, the comments you put seems to be relevant to my other issue.

**Comment by davidwaters33** [comment]
I don't understand why this matters?  Looking at your expected behaviour, what is the queue header?  Why would this be there?  How does this impact system behaviour?

**Comment by Kusnaditjung** [comment]
Hi, the queue header thing is just a suggestion. Sori, I am just delayed in my thinking, I think the solution you suggest should work as well. However, I think Kainos already have some work to put the ITK envelope in the FHIR message header resource instead. I think that would solve this issue (if they output the interaction as well).

**Comment by Kusnaditjung** [comment]
after the 0.2.0 release, the FHIR message header output does not contain interaction so, it seems to need to rely on the REFT participation, as suggested, to decide whether for ACTION or for INFORMATION.

**Comment by Kusnaditjung** [comment]
@davidwaters33  just a question: is the participant REF can be used reliably in this case because PRCP (primary recipient) is mandatory (1..n)  while REFT (participant) is optional (0..n). I have not seen any documentation that mandates the REFT must match with the PRCP. What happens is NHS111 refer back patient to both GP and some other surgery clinic, both as primary, and the participant only have surgery clinic. Is this scenario is likely and do we need to consider? I just wonder if this mechanism will be more robust than using the ITK interaction?

**Comment by michael-kainos** [comment]
MessageHeader.reason will be populated with these codes, will aim to implement this in the next release.
