### ISSUE TITLE
The FHIR output message does not have NHS identifier or identifiers in the Patient Resource

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#118]
**Description**

In the FHIR Output, there is no NHS Number in the patient resources, while in their CDA input there is an unverified NHS number.  The NHS number is important for the workflow in the application for the patient matching stage.

```xml

<patientRole classCode="PAT">
                                <templateId extension="COCD_TP145201GB01#PatientRole"
                                            root="2.16.840.1.113883.2.1.3.2.4.18.2"/>
                                <id extension="K12345" root="2.16.840.1.113883.2.1.3.2.4.18.24"
                                    assigningAuthorityName="Medway NHS Foundation Trust"/>
                                <id extension="993254128" root="2.16.840.1.113883.2.1.3.2.4.18.23"/>

```
the OID for NHS number is 2.16.840.1.113883.2.1.4.1, which does not exist in the sample, but there are other two identifiers which is 2.16.840.1.113883.2.1.3.2.4.18.23 = 993254128 (unverified NHS number), and local identifier (2.16.840.1.113883.2.1.3.2.4.18.24 = K12345).

I think there is a rule for CDA receiving **CR40.2**  (ITK CDA functional (Receiver requirements)), which say when the OID for the patient identifier is an unverified NHS number, the patient matching state should mark the document so the user is aware that the document is matched based on unverified NHS number. 

But now, there are no identifiers in the output while there are identifiers in the original CDA documents. 

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the valid a CDA in the payload, and send
* Inspect the FHIR patient resource, there is no identifiers output. 

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
High, impact on supplier integration

**Priority**
Not urgent

**Expected Behavior**
The FHIR patient resource has identifiers in the output. 
There are there possible identifiers, which (1) verified nhs number, (2) unverified nhs number and (3) local identifier.

**Comment by michael-kainos** [comment]
Fixed
Will be available in 0.2.0 release

**Comment by michael-kainos** [comment]
@Kusnaditjung please confirm this can be closed

**Comment by Kusnaditjung** [comment]
yep this can be closed
