### ISSUE TITLE
Duplicate FHIR Patient resources in the output

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#119]
**Description**

The patient resource in the FHIR output is duplicated (have more than one the same patient resource)

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the valid a CDA in the payload, and send
* Inspect the FHIR patient resource, there are more than one (duplicate)

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low

**Priority**
Not urgent

**Expected Behavior**
Only one resource per item in the FHIR output, including patient resource.

**Comment by dawidskainos** [comment]
Fixed in https://gpitbjss.atlassian.net/browse/NIAD-579.
Will be available in 0.2.0 release

**Comment by michael-kainos** [comment]
@Kusnaditjung please confirm if this can be closed

**Comment by Kusnaditjung** [comment]
yup
