### ISSUE TITLE
Missing element for UI rendering

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#123]
**Description**
I attempt to render the FHIR transformation output using the old stylesheet (used to be  pre-assured transformation stylesheet), I cannot retrieve some important element as it is not mapped. There is also some other missing element that is not mandatory in the CDA. 
Element missing:
- author's job role name, and organization name
- care setting location, and type
- responsibility party job role name
- Document ID
- VerstionNumber;
- CopyRecipient.
- NHSnumber (this is to be supplied in 0.2.0)

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the valid a CDA in the payload, and send
* cannot retrieve those missing elements.

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low

**Priority**
high may impact integration

**Expected Behavior**
The FHIR output has those missing elements.

Rendered from CDA
![image](https://user-images.githubusercontent.com/2870531/96711217-1f3bce00-1395-11eb-913b-f82d18546351.png)

Rendered from FHIR
![image](https://user-images.githubusercontent.com/2870531/96711078-e56ac780-1394-11eb-99e9-47b66be86d2c.png)

**Comment by Kusnaditjung** [comment]
Above is the basis of the Simple UI implementation and will become the basis for meddbase implementation later on. Some of them are for the summary report header, some of them for the administrative view (there is receiving requirements for the administrative header). Though I don't use the stylesheet for the simple UI implementation, I have used the elements included as the basis for the implementation.

**Comment by michael-kainos** [comment]
We understand that you are asking is UI rendering part of the accreditation process for NHS111, which it is not. Based on this we think we can close this, please confirm. @Kusnaditjung

**Comment by Kusnaditjung** [comment]
ok, based on the reply, my understanding is I will need to omit some of the current rendering parts, as they are not available on the adapter at the moment though they are on the original CDA. There is one element however I think it will only make sense if they are available such VersionNumber. This element and SetID are used to decide whether the CDA document is a replacement document or the original document. Can you confirm this for me with NHSD (e.g whether NHS 111 provider may send a replacement document, otherwise we may need to assume it will be always = 1)

**Comment by michael-kainos** [comment]
@Kusnaditjung closing as discussed. This is now fixed.
