### ISSUE TITLE
Clinical Document code not mapped

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#125]
**Description**

The CDA document has a 'code' element which can be used to decide the document type (SNOMED code). I assume there can multiple types of NHS 111 document types? The CDA receive requirement has a SHOULD requirement that used this as the document data for ordering. Though it is not a mandatory requirement, I just wonder if this can be mapped in the FHIR output as well. This is more a question if there is no action that need to be taken, this issue can be closed straightaway. 

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
Send valid CDA

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
high

**Priority**
low

**Expected Behavior**
can retrieve CDA code element

**Comment by michael-kainos** [comment]
![Screenshot 2020-10-28 at 15 50 36](https://user-images.githubusercontent.com/56648591/97461126-5b42d600-1935-11eb-88cf-f00f6ca6fae2.png)
Closing this
