### ISSUE TITLE
Episode of care in Encounter seems to be taken out, where the care setting location etc are mapped to ?

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#130]
**Description**

Version 0.2.0 seems to eliminate the episode of care, but my question is more where 
Encounter Type, time, care setting location, and type is mapped to? Some of them already missing in version 0.1.0, but with the episode of care is taken out, where some of the elements went now.

They may be important to be shown to users, and these elements are in the CDA transformation stylesheet output. 

**Component**
NHS111 adapter

**Version**
0.2.0

**Step to Reproduce**
-Send valid CDA
- could not find a care setting location, type, and responsibly party, encounter time, and encounter type.

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
high

**Priority**
low

**Expected Behavior**
Should be able to retrieve care setting location and related elements

**Comment by michael-kainos** [comment]
These should now have new mapping in the encounter resource. We update the mappings.

**Comment by michael-kainos** [comment]
@Kusnaditjung closing as discussed
