### ISSUE TITLE
Clinical document schema validation

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#131]
**Description**

The NHS 111 CDA message should be a valid NHS 111 CDA message, there is two schema validation that needs to be performed against the message. 

- Generic CDA schema validation, schema validation against on wire generic CDA format which is POCD_MT000002UK01.xsd

- NHS111 message schema validation, need to transform generic CDA to templated format and validate against schema for NHS 111 message (POCD_MT200001GB02.xsd), which is specified in the ClinicalDocument->npfitlc:messageType (need also to make sure this element is POCD_MT200001GB02, as the adapter only process NHS111)

These validations can be found in the NPFIT-FNT-TO-TAR-0081.03 CDA Document Technical Requirements v2.0.pdf from **NHS Interoperability Toolkit CDA Functional Requirements** pack and can be downloaded from TRUD. 

My observation is that the templated schema may not be performed, as there is an element in the assurance ITK Sample which is not in the POCD_MT200001GB02 message template, but they are processed as just a valid NHS 111 message. The suspect element is custodian telecom and addr , both elements are not in the specification, but they present in the example and are processed as just a valid NHS 111 message.  

There are a number of a possible explanation of this is 
(1) the example does not reflect the live scenario, e.g handcrafted.
(2) The sender does not validate the message before sending (which against the assurance process)
(2) the sender validates against different NHS111 DMS, but apparently not the one currently in TRUD or Integrated Urgent Care DMS on the internet. 
(4) I reserve that my understanding of the HL7 V3 CDA RIM model may be wrong or flaw, and happy to be corrected. 

```xml
   <custodian typeCode="CST">
              <npfitlc:contentId root="2.16.840.1.113883.2.1.3.2.4.18.16"
                                 extension="COCD_TP145018UK03#AssignedCustodian"/>
              <assignedCustodian classCode="ASSIGNED">
                <templateId root="2.16.840.1.113883.2.1.3.2.4.18.2"
                            extension="COCD_TP145018UK03#AssignedCustodian"/>
                <representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
                  <templateId root="2.16.840.1.113883.2.1.3.2.4.18.2"
                              extension="COCD_TP145018UK03#representedCustodianOrganization"/>
                  <id root="2.16.840.1.113883.2.1.3.2.4.19.1" extension="5L3"/>
                  <name>Broomfield Foundation Trust</name>
                  <telecom use="WP" value="tel:0123476895"/>
                  <addr use="WP">
                    <streetAddressLine>Broomfield Hospital</streetAddressLine>
                    <streetAddressLine>Bocking End</streetAddressLine>
                    <postalCode>CM7 9AB</postalCode>
                    <city>Braintree</city>
                    <county>Essex</county>
                    <country>UK</country>
                  </addr>
                </representedCustodianOrganization>
              </assignedCustodian>
            </custodian>
```

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
* Put the the example of CDA in the ..\service\src\integration-test\resources\xml\ITK_Report_request.xml
* Send the message, the response should fail with a templated schema validation error.

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**

The response returns a SOAP Fault (as a consequence of sync mode of the adapter) with error text and/or diagnostic:

* CDA Message Definition Schema validation failure. Detail: "{0}" => if templated cda validation
The OID for this error is 2.16.840.1.113883.2.1.3.2.4.17.227, and the error code can be found from the below link.
See point to point error documentation, NPFIT-FNT-TO-TAR-0083 02 CDA Interoperability - Point to Point Error Codes v1.0 from **NHS Interoperability Toolkit CDA Functional Requirements** pack.

**Comment by michael-kainos** [comment]
The correct valid message has now been updated in the repository. This has now been fixed. We will not be adding NHS111 message schema validation to the adapter, this will be raised in the backlog as a possible future fix.
