### ISSUE TITLE
Question about ITK addressList not mapped

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#132]
**Description**
This is more a question and confirmation. The ITK assurance sample is tagged like this

```xml
 <!-- the address list is not needed, as the end point has been looked up and is in the SOAP header
                <itk:addresslist>
                    <itk:address uri="urn:nhs-uk:addressing:ods:EM396"/>
                </itk:addresslist> -->
                <!-- an audit identification of the sending organisation - use the send organisation's ODS site code -->
```

So it seems the address list is not mapped. I think the comment is based on the assumption, every organization will have its own adapter endpoint.  

Med base plan to deploy just one adapter for all organizations that using NHS 111, as there is no value to deploy many adapters (deployment and configuration burden). In that case, the ITK **addresslist** will be essential to map to which organization the message needs to pass to. I believe this element should be mapped as they are in the original CDA document unless the element deems absolutely unnecessary in any circumtances.   

Can you confirm if my assumption is correct, or there is something missing in my assumption? 

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**
- Send a valid message
- inspect that ITK AddressList is  not mapped

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**
ITK addressList should be mapped.

**Comment by michael-kainos** [comment]
This will be implemented in the next release, itk:address uri will be mapped to destination in the header

**Comment by kategill** [comment]
Address lists from 111 always come in this format:
<addresslist>
<address uri="urn:nhs-uk:addressing:ods:20000729"/>
<address type="2.16.840.1.113883.2.1.3.2.4.18.44" uri="2000072936"/>
</addresslist>

ODS code is not reliable- it is often perfectly fine for GP practice systems, however is sometimes not accurate for branch sites etc.  The second URI is the DOS Service ID.  It would be best to send both through in FHIR, but use the Service id as config receiving end to work out where to put this in the right place ie specific GP instance on a shared system etc.

**Comment by Kusnaditjung** [comment]
The version 0.3.0 only outputs the first one, not sure about the second one as the input XML only have the first one only.

**Comment by michael-kainos** [comment]
@Kusnaditjung  as discussed this can be closed
