### ISSUE TITLE
Agreement on UI rendering elements

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#133]
For NHS 111 work in Meddbase, we have taken the approach to use a simple UI approach to demonstrate what is displayed in the UI to the users. 

However, the requirements for the UI rendering is not coming from the end-users, but from NHS 111 assurance process. I just wonder if we can agree on what should be displayed for the UI, I think before the adapter work, the only requirements for UI rendering is revolving around the transformation stylesheet, but with the adapter work, it is not possible to use the stylesheet anymore. But we can still use it to identify elements that need to be displayed.  

For NHS adapter work, Initially, I have used the old stylesheet to identify elements that need to be output. 
David waters give me the Integrated Urgent Care stylesheet, and it seems it outputs more elements. 

So, before I am going to do more work, can we agree on this issue on whether
(1) the old stylesheet should be enough to identify what elements should be displayed in the UI
     (so I will do no more work as that is what I have done at the moment)
(2) using the new stylesheet to identify what elements should be displayed in the UI
(3) a new agreement on what elements should be displayed as MUST (or probable categorized as MUST and SHOULD, with SHOULD can be decided by the main application), and this should be documented as part of the adapter work and feedback to the accreditation process for new suppliers using NHS111 adapter.

I think the adapter work should be in async with the whole accreditation process for NHS111, including on the application side, and thus the UI rendering should be relevant to this indirectly.

Just let me know the decision.

Attached is the output from the new stylesheet, the output from the old stylesheet can be seen in #123

![image](https://user-images.githubusercontent.com/2870531/97696204-22be0c00-1a9d-11eb-9bf4-ed87d3b26a0e.png)
![image](https://user-images.githubusercontent.com/2870531/97696333-5305aa80-1a9d-11eb-8354-7defe371db07.png)

**Comment by michael-kainos** [comment]
We understand that you are asking is UI rendering part of the accreditation process for NHS111, which it is not. Based on this we think we can close this, please confirm. @Kusnaditjung

**Comment by Kusnaditjung** [comment]
ok, based on the reply, my understanding is I will need to omit some of the current rendering parts, as they are not available on the adapter at the moment though they are on the original CDA. There is one element however I think it will only make sense if they are available such VersionNumber. This element and SetID are used to decide whether the CDA document is a replacement document or the original document. Can you confirm this for me with NHSD (e.g whether NHS 111 provider may send a replacement document, otherwise we may need to assume it will be always = 1)

**Comment by davidwaters33** [comment]
@Kusnaditjung What do you do with the `MessageHeader` that the adapter outputs?

**Comment by Kusnaditjung** [comment]
@davidwaters33 At the moment, the message header carries two ITK elements, addressList and ITK Interaction (as adapter 0.3.0, I think 0.4.0 should be the same),  the addressList is used to route the report to the correct recipient organization, while the ITK interaction is used to decide whether the report required action (if primary type interaction), or only for the information to the recipient (if copy type interaction). Please check if this is the correct usage.

**Comment by davidwaters33** [comment]
@Kusnaditjung That's fine - I was more asking what the receiving organization will do with it?  Basically, if they are then going to store in a FHIR server, we can look at how the normal FHIR way of doing versions of resources works (basically, this would be a history of the `Bundle`) but if they aren't doing that, we may need to be more explicit in how we carry/express any version number

As an aside, this may not be necessary, as we don't believe that any supplier will ever send replacement documents, but I'm checking that, as well

**Comment by Kusnaditjung** [comment]
@davidwaters33, ah okay, so one element (address list) is used to route by the integration engine and also stored in the recipient organization audit (as the address list may contain more information other than the ODS), and the interaction type is used in the organization inbox workflow for the report action.  

For the FHIR bundle history version, we don't store them in an FHIR server, and this is an unlikely scenario for us as this is a transient FHIR (there is no actual server that outputs the NHS 111 report which is also an FHIR server), so we treat them as a mere message wrapper rather than the actual FHIR resources.  


The VersionNumber I am referring to is the VersionNumber of the CDA,  if they are going to be mapped in the FHIR output, they can be in the extension (either Bundle or composition), or any other places that you think may signify them better.   

I have one question as I have no idea what the answer is. Who normally implements the  NHS 111 supplier systems or call center, is it NHS or any parties can implement them based on the specification? I think if the answer is NHS then NHSD can override the specification and make that assumption, but if the supplier system can be implemented by any parties then it is futile to make that assumption, as the new supplier may not do the same as previous suppliers did unless NHSD also changes the specification at the same time.

**Comment by davidwaters33** [comment]
@Kusnaditjung So, if you don't store the `Bundle`, what would you do with an updated report if you got one?  How would you recognise it was an update, if you didn't have the original stored?

**Comment by davidwaters33** [comment]
With regard to the second question, 111 supplier systems are built by third parties

**Comment by Kusnaditjung** [comment]
@davidwaters33 hi, sori I think you misunderstand what I mean. We don't have a special FHIR server to store the bundle, but we do store the FHIR in our audit in integration service, and more importantly, when we send the document to the main application in our format, we provide the metadata data with that, e.g equivalent to SetId and Version Number, so using this metadata we can track if there is a replacement coming in in the future.   For the second question, if the NHS 111 is built by third parties, that make this issue more important, as the third parties develop based on specs, and not necessarily follow the exact same path of the previous implementation.

**Comment by davidwaters33** [comment]
Adapter will be changed to map versionid to the Bundle.identifier

**Comment by michael-kainos** [comment]
@Kusnaditjung closing as discussed. This is now fixed.
