### ISSUE TITLE
Validation: Missing security time stamp created and expires element returns 2200 internal error & Error Text and Diagnostic Text are swapped

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#134]
**Description**
(1) When missing :
    - soap security->timestamp->created 
    - soap security->timestamp->expires

     this should return soap fault with error 1000, soap validation failed like others
    at the moment it returns soap fault 2200, with internal error

(2) Generally it seems the ErrorText and ErrorDiagnosticText get swap when returning 'soap validation failed' and 'Internal Error', but correct when returning 'This is not a valid XML message'
   e.g 
     ErrorText should 'Soap validation failed' (generic, general)
     ErrorDiagnosticText should be e,.g 'invalid timestamp' (more specific)
  at the moment, the 'soap validation failed' in the errorDiagnosticText. 

**Component**
NHS111 adapter

**Version**
0.2.0

**Step to Reproduce**
* Put a valid ITK assurance example
* remove security -> timestamp -> created, or security ->timestamp- >expires
* send the message
* it returns soap fault with 2200, internal error... this should be 1000, 'soap validation failed'

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**

it should return soap fault, 1000, with 'soap validation failed'

**Comment by michael-kainos** [comment]
Issue 1 - closing with low priority, this will be raised in a backlog for a possible future fix
Issue 2 - We believe we are populating the mentioned fields correctly, please raise a separate issue if you believe this not to be the case
