### ISSUE TITLE
Validation: Invalid message with at least one valid SOAP still processed as success

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#135]
**Description**

When the message is not valid, but contains at least valid one valid SOAP message, it still processed as success

**Component**
NHS111 adapter

**Version**
0.2.0

**Step to Reproduce**
- send message with this format:

``` XML
<NHS111>

<Document>
    This is invalid SOAP
</Document>

<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   this is invalid soap (just left it empty)
</s:Envelope>

<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   valid SOAP (replace this with valid soap)
</s:Envelope>

```

- it still shows as success

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**

it should return soap fault, 1000

**Comment by michael-kainos** [comment]
closing with low priority, this will be raised in a backlog for a possible future fix
