### ISSUE TITLE
Validation: Missing ITK header service attribute returns 2200 internal error

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#137]
**Description**

When an ITK header service attribute missing, an internal error is returned (2200). 

**Component**
NHS111 adapter

**Version**
0.2.0

**Step to Reproduce**
- get valid ITK assurance message
- remove the ITK header service attribute
- send message
- internal error, 2200 soap fault returned

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low, 

**Priority**
Not urgent

**Expected Behavior**

it should return : 
(1) soap fault, 1000
(2) or, CDA point to point error with OID 2.16.840.1.113883.2.1.3.2.4.17.227, with code 40013
![image](https://user-images.githubusercontent.com/2870531/97852139-42983e80-1cee-11eb-8878-7b4ddbcc8262.png)

**Comment by AndrewGuiseley** [comment]
Hi @Kusnaditjung  - this is an extreme edge case scenario, both SOAP error codes 1000 and 2200 are equally applicable in this scenario and so we would propose no change.

**Comment by michael-kainos** [comment]
closing with low priority, this will be raised in a backlog for a possible future fix
