### ISSUE TITLE
TKW Assurance: for negative tests,  the error response need a proper space between attributes for the Envelope element

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#150]
**Description**
For TKW negative tests, all error response that coming back fails the validation.
The reason is below:

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="http://www.w3.org/2005/08/addressing"xmlns:itk="urn:nhs-itk:ns:201005">

where attributes should be properly separated like below (see a space in front of xmlns:itk)

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="http://www.w3.org/2005/08/addressing"     xmlns:itk="urn:nhs-itk:ns:201005">

**Component**
NHS111 adapter

**Version**
0.5.0

**Step to Reproduce**
- make sure the adapter is running, with PEM111_SOAP_SEND_TO=[nigx endpoint]/report
- copy negative file template from **TKW/contrib/ITK_2_01_Test_Messages/111/Negative_111_Templates**
  to **\TKW\config\ITK_111\TestRun\Testfiles**
- run 1.Clear_Folders.bat
- run 3.Transmit_TestFiles.bat
- run 4. Validate_All_Results.bat
- open HTML file in **TKW\config\ITK_111\validator_reports**
- see the result for any msg2 messages.

RROR: Exception thrown validating file 127.0.0.1_sent_0AE7A8CD-3611-11EB-AB9C-6D49B34CDC15_at_20201204091359.103.log_msg2.xml : net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 111; Element type "s:Envelope" must be followed by either attribute specifications, ">" or "/>". -- net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 111; Element type "s:Envelope" must be followed by either attribute specifications, ">" or "/>".

**Test Data**
from TKW assurance 

**Preconditions**
None

**Environment**
local environment

**Severity**
Medium 

**Priority**
Not Urgent

**Expected Behavior**

The attribute in the Envelope should be properly separated.

[TKWComplete.zip](https://github.com/nhsconnect/integration-adaptor-111/files/5642032/TKWComplete.zip)

**Comment by dawidskainos** [comment]
The actual 111 response is:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="http://www.w3.org/2005/08/addressing"
            xmlns:itk="urn:nhs-itk:ns:201005">
    <s:Header>
        <a:MessageID>B6B7F41A-5C37-4F42-8B75-F1052BF872EA</a:MessageID>
        <a:Action>http://www.w3.org/2005/08/addressing/soap/fault</a:Action>
        <a:To>http://www.w3.org/2005/08/addressing/anonymous</a:To>
    </s:Header>
    <s:Body>
        <s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>A client related error has occurred, see detail element for further information</faultstring>
            <faultactor>http://source.of.fault.example.com</faultactor>
            <detail>
                <itk:ToolkitErrorInfo>
                    <itk:ErrorID>383D73FB-0472-4809-B110-958707BDC5D8</itk:ErrorID>
                    <itk:ErrorCode codeSystem="2.16.840.1.113883.2.1.3.2.4.17.268">1000</itk:ErrorCode>
                    <itk:ErrorText>Manifest and payload items IDs don't match</itk:ErrorText>
                    <itk:ErrorDiagnosticText>Soap validation failed</itk:ErrorDiagnosticText>
                </itk:ToolkitErrorInfo>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```

TKW then transforms is before validation. After transformation it looks like:
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="http://www.w3.org/2005/08/addressing"xmlns:itk="urn:nhs-itk:ns:201005"><s:Header><a:MessageID>B6B7F41A-5C37-4F42-8B75-F1052BF872EA</a:MessageID><a:Action>http://www.w3.org/2005/08/addressing/soap/fault</a:Action><a:To>http://www.w3.org/2005/08/addressing/anonymous</a:To></s:Header><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>A client related error has occurred, see detail element for further information</faultstring><faultactor>http://source.of.fault.example.com</faultactor><detail><itk:ToolkitErrorInfo><itk:ErrorID>383D73FB-0472-4809-B110-958707BDC5D8</itk:ErrorID><itk:ErrorCode codeSystem="2.16.840.1.113883.2.1.3.2.4.17.268">1000</itk:ErrorCode><itk:ErrorText>Manifest and payload items IDs don't match</itk:ErrorText><itk:ErrorDiagnosticText>Soap validation failed</itk:ErrorDiagnosticText></itk:ToolkitErrorInfo></detail></s:Fault></s:Body></s:Envelope>`

All whitespaces are removed and as a result we have an invalid XML.

I'll modify 111 response so it passes TKW tests just to avoid any issues in the future.

It will be releases in 0.5.1

**Comment by Kusnaditjung** [comment]
upon 0.5.1 this can be closed now
