### ISSUE TITLE
TKW Assurance: Negative tests return positive responses

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#151]
**Description**
From all negative tests, there are 4 tests that return positive responses (which are incorrect responses)
Here is the result summary in the Results folder file (the ZIP file attached below)

..\transmitter_sent_messages\127.0.0.1_sent_0AE7A8CD-3611-11EB-AB9C-6D49B34CDC15_at_20201204091359.103.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0BCA4094-3611-11EB-92D8-EF484D17A112_at_20201204091400.589.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0CA51046-3611-11EB-A7DE-71F13CF045DD_at_20201204091402.023.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0D704F0D-3611-11EB-9070-ED90B48AA8DE_at_20201204091403.357.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0E418204-3611-11EB-A3A3-594512194EA5_at_20201204091404.733.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0F0D5D9A-3611-11EB-B953-B34716FF64D0_at_20201204091406.064.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_0FD7B27E-3611-11EB-B9C5-478A8BBE996D_at_20201204091407.396.log Fail
**..\transmitter_sent_messages\127.0.0.1_sent_11DB7158-3611-11EB-9F1E-172476EB82CB_at_20201204091410.769.log Pass**
..\transmitter_sent_messages\127.0.0.1_sent_13C0D366-3611-11EB-963C-716BACFD34AE_at_20201204091413.954.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_14CF364F-3611-11EB-9862-1B89466C933A_at_20201204091415.711.log Fail
**..\transmitter_sent_messages\127.0.0.1_sent_15EDC511-3611-11EB-BC90-4FFD8D2629B0_at_20201204091417.601.log Pass**
..\transmitter_sent_messages\127.0.0.1_sent_16FF351F-3611-11EB-82C0-A3E1139A586C_at_20201204091419.391.log Fail
**..\transmitter_sent_messages\127.0.0.1_sent_17F30B44-3611-11EB-9681-3BF606CC832A_at_20201204091420.991.log Pass**
..\transmitter_sent_messages\127.0.0.1_sent_18F38B59-3611-11EB-8D21-CB48DBA7D970_at_20201204091422.673.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_1A008EEA-3611-11EB-8484-4153DFDE9BD4_at_20201204091424.435.log Fail
**..\transmitter_sent_messages\127.0.0.1_sent_1AEFD0A3-3611-11EB-8125-0D431B01592C_at_20201204091426.004.log Pass**
..\transmitter_sent_messages\127.0.0.1_sent_1C42DD30-3611-11EB-BF60-A3384E0EC502_at_20201204091428.227.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_1D3EF02C-3611-11EB-AB01-B70C2A7A1975_at_20201204091429.875.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_1E222505-3611-11EB-87EE-D50B2344B0A2_at_20201204091431.365.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_1F162195-3611-11EB-8273-D3B18625B00D_at_20201204091432.965.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_20022ED0-3611-11EB-816E-2331A72DD8ED_at_20201204091434.513.log Fail
..\transmitter_sent_messages\127.0.0.1_sent_null_at_20201204091409.342.log Fail

**Component**
NHS111 adapter

**Version**
0.5.0

**Step to Reproduce**
- make sure the adapter is running, with PEM111_SOAP_SEND_TO=[ngix endpoint]/report
- copy negative file template from **TKW/contrib/ITK_2_01_Test_Messages/111/Negative_111_Templates**
  to **\TKW\config\ITK_111\TestRun\Testfiles**
- run 1.Clear_Folders.bat
- run 3.Transmit_TestFiles.bat
- see report summary in **TKW\config\ITK_111\TestRun\Results**

**Test Data**
from TKW assurance 

**Preconditions**
None

**Environment**
local environment

**Severity**
Medium 

**Priority**
Not Urgent

**Expected Behavior**

All responses should be failed

[TKW.zip](https://github.com/nhsconnect/integration-adaptor-111/files/5641993/TKW.zip)

**Comment by AndrewGuiseley** [comment]
Hi @Kusnaditjung, can you send the validator reports directory please for this test run so l can investigate further. Thanks.

**Comment by Kusnaditjung** [comment]
I have attached the directory ... see the TKW.zip at the bottom of the issue page... let me know if you get everything you need from that..

**Comment by AndrewGuiseley** [comment]
Thanks. To expedite this as quickly as possible can you just list the test names/negative scenarios that you are having an issue with please

**Comment by Kusnaditjung** [comment]
Here is the tests: 
![image](https://user-images.githubusercontent.com/2870531/101367422-0e401100-389e-11eb-87b9-e6a082bb0a73.png)

**Comment by AndrewGuiseley** [comment]
Hi @Kusnaditjung

SO_EXHMDU - this should return a positive response - the System should accept but ignore foreign SOAP header with mustUnderstand attribute not set. 
SO_EXHEAD - this should return a positive response - the System should accept but ignore foreign SOAP header with no "mustUnderstand" attribute
SO_INVUSR - not sure why you are executing this as this test is not applicable - TLS Authentication is, so SOAP username is not checked in any way
GeneralPractitionerRecipient_Prim_ackreq_fail - do you mean the 111_GP_REC_PRIM? If so this should return a positive response

**Comment by Kusnaditjung** [comment]
Hi, in that case, the TKW somewhat misleading... all the templates are under Negative_111_Template in TKW\contrib\ITK_2_01_Test_Messages\111 so I assume all of them need to return negative responses. This issue can be closed if that is the case.

**Comment by Kusnaditjung** [comment]
I found out the offending bundle is ambulance receiver tests, if I select this bundle, the three test cases will fail. Michael Martin has sent me the test cases to test for NHS 111. If I apply the test cases selective based on the tests send to me, all test cases pass. So this issue can be closed as the result.

**Comment by AndrewGuiseley** [comment]
Hi @Kusnaditjung - ok thanks a lot
