### ISSUE TITLE
No validation if the message is not of  NHS 111 type.

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#91]
**Description**

When changing the document type of non-NHS 111 types of reports, the response is still successful, and the document appears in the queue.

**Component**
NHS111 adapter

**Version**
0.1.0

**Step to Reproduce**

- Put the valid a CDA in the payload
- Change :
       ClinicalDocument->npfitlc:messageType@extension to something else, 

**Test Data**
Any data

**Preconditions**
None

**Environment**
local environment

**Severity**
Low,

**Priority**
Not urgent

**Expected Behavior**
It should be a SOAP Fault ((as a consequence of sync mode of the adapter) with error description  and/or diagnostic text:
'Message Type not supported here'
with error Code 430, and OID = 2.16.840.1.113883.2.1.3.2.4.17.227

(see NPFIT-FNT-TO-TAR-0083 02 CDA Interoperability - Point to Point Error Codes v1.0.pdf in the ITK CDA functionality pack)

**Comment by michael-kainos** [comment]
Please retest this in the next 111 image release. Status is DEFERRED

**Comment by michael-kainos** [comment]
@Kusnaditjung see before attached requirements and test cases document in issue
https://github.com/nhsconnect/integration-adaptor-111/issues/115.
Validation of this particular element is easy to add yet not required by “TK2.2-Supplier Certified Requirements Coverage v8.5-NHS111Receiver.xls”.

**Comment by Kusnaditjung** [comment]
cannot seem to find the documen mentioned ?

**Comment by michael-kainos** [comment]
See comments here:
https://github.com/nhsconnect/integration-adaptor-111/issues/115#issuecomment-712828392

**Comment by Kusnaditjung** [comment]
oh, you mean content validation ?? though the content validation can be ignored, for now, this particular element bear significant importance, this element specifies what templated message this message should conform to (in our case it should conform to NHS 111 messages), so when you need to validate against the schema you will need this element to be correct, this is the only element in the ClinicalDocument that say this message is an NHS 111 message and say which message type it needs to conforms to. I don't think #115 can apply to this.

**Comment by michael-kainos** [comment]
Only expect 111 accredited system supplier to send cda documents that are of type nhs 111
