### ISSUE TITLE
Attachment or ObservationMedia is not translated into FHIR

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-111#95]
Cannot find the translation of attachment (ObservationMedia) in the FHIR response, and cannot found the mapping either in the mapping document. 

I think this particular element is important and may pose a clinical safety risk if it is contained in the original document but not in the FHIR response.

**Comment by Kusnaditjung** [comment]
Though there is no mapping in the mapping document, I think this element quite important and may pose a clinical safety issue if it is in the original document but not in the FHIR response. I think it probably maps to Media in FHIR R4.

**Comment by michael-kainos** [comment]
Will investigate, Status is ASSIGNED

**Comment by Kusnaditjung** [comment]
From the discussion with NHSD architect (David Waters and Adam lee), they have mentioned that attachments should not be used when sending the document in NHS 111, and if the recipient received them, they can choose to do whatever to do with that. At the moment, the adapter ignores attachments and not translate any of the translation. This issue thus can be closed.
